# https://rust-lang.github.io/rustfmt/
hard_tabs = false
tab_spaces = 2
trailing_comma = "Always"
color = "Always"
comment_width = 100
empty_item_single_line = true
fn_args_layout = "Tall"
max_width = 100
fn_single_line = true
force_explicit_abi = true
format_code_in_doc_comments = true
format_strings = true
merge_imports = true
normalize_doc_attributes = true
group_imports = "StdExternalCrate"
reorder_modules = true
trailing_semicolon = true
wrap_comments = true
